spring:
  application:
    name: auth-server
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    env:
      enabled: true
    logfile:
      enabled: true
    loggers:
      enabled: true
    mappings:
      enabled: true
    configprops:
      enabled: true
    scheduledtasks:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
logging:
  file:
    name:  /logs/application/gateway.log
server:
  port: 8081